### ISSUE TITLE
RARBG imdb special search type

### ISSUE THREAD

**Issue by JuniorJPDJ** [mabakay/torrenter#1]
Hi,
I don't know if you know that, but RARBG has special search type - by IMDB ID.
It shows movie title etc.
You may be interested in adding this search type instead of title + date.
Example: https://rarbgmirror.org/torrents.php?imdb=tt4154756

**Comment by mabakay** [comment]
Hi,
Thanks for the hint. Add-on has simple code, it extracts and send title + year to every search site which support that method (simply everyone). Thanks for it, it is very flexible. If you need to add/change search list you need only to add new url to list.

Implementing site specific search would be much more time demanding. Additionally from time to time this list changes because of temporary or permanently unavailability of sites on it what makes site specific search even less profitable.

Do you notice less accurate search results in actual method than by using IMDB ID on RARBG site?

**Comment by JuniorJPDJ** [comment]
Actually how you implemented it is totally satisfying.
Everything seems to be ok with results obtained with your method, the only difference seems to be that search by IMDB ID shows movie info in search page.

**Comment by mabakay** [comment]
Done in latest 2.2.0 version :-)
